contacts/contact/urls.py
from django.urls import path
from contact.views import (
    PersonListView,
    PersonAddView,
    UpdatePersonView,
    PersonDeleteView,
    PhoneAddView,
    EmailAddView,
    PhoneDeleteView,
    EmailDeleteView,
)

app_name = 'contact'
urlpatterns = [
    path('list', PersonListView.as_view(), name='list'),
    path('add', PersonAddView.as_view(), name='person-add'),
    path('<int:id>/update', UpdatePersonView.as_view(), name='person-update'),
    path('<int:id>/delete', PersonDeleteView.as_view(), name='person-delete'),
    path('<int:id>/phone/add', PhoneAddView.as_view(), name='phone-add'),
    path('phone/<int:id>/delete', PhoneDeleteView.as_view(), name='phone-delete'),
    path('<int:id>/email/add', EmailAddView.as_view(), name='email-add'),
    path('email/<int:id>/delete', EmailDeleteView.as_view(), name='email-delete'),
]

contacts/contacts/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', home_view, name='home'),

    path('contact/', include('contact.urls')),
]

contacts/contact/models.py
from django.db import models
from django.db.models import Q
from django.core.validators import RegexValidator
from django.urls import reverse


class ContactQuerySet(models.QuerySet):
    def search(self, query=None):
        lookup = (
            Q(name__icontains=query) |
            Q(surname__icontains=query) |
            Q(email__email__icontains=query) |
            Q(phone__phone__icontains=query)
        )
        return self.filter(lookup)


class ContactManager(models.Manager):
    def get_queryset(self):
        return ContactQuerySet(self.model, using=self._db)

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query=query)


class Person(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)

    objects = ContactManager()

    def update_url(self):
        return reverse('contact:person-update', kwargs={'id': self.id})

    def delete_url(self):
        return reverse('contact:person-delete', kwargs={'id': self.id})

    def phone_add_url(self):
        return reverse('contact:phone-add', kwargs={'id': self.id})

    def email_add_url(self):
        return reverse('contact:email-add', kwargs={'id': self.id})


class Phone(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. \
            Up to 19 digits allowed."
        )
    phone = models.CharField(validators=[phone_regex], max_length=20)

    def delete_url(self):
        return reverse('contact:phone-delete', kwargs={'id': self.id})


class Email(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    email = models.EmailField()

    def delete_url(self):
        return reverse('contact:email-delete', kwargs={'id': self.id})

contacts/pages/models.py
from django.db import models

# Create your models here.

contacts/contact/forms.py
from django import forms
from .models import Person, Phone, Email


class PersonModelForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = [
            'name',
            'surname'
        ]


class PhoneModelForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = [
            'phone'
        ]


class EmailModelForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = [
            'email'
        ]

contacts/contact/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView
)
from .models import Person, Phone, Email
from .forms import (
    PersonModelForm,
    PhoneModelForm,
    EmailModelForm
)


class PersonListView(ListView):
    template_name = 'list.html'
    queryset = Person.objects.all()

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        queryset = self.queryset
        if query is not None:
            queryset = Person.objects.search(query=query)
            for person in queryset:
                person.phone = Phone.objects.filter(person=person)
                person.email = Email.objects.filter(person=person)
        else:
            queryset = Person.objects.all()
            for person in queryset:
                person.phone = Phone.objects.filter(person=person)
                person.email = Email.objects.filter(person=person)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['query'] = self.request.GET.get('q')
        return context


class PersonAddView(CreateView):
    template_name = 'contact/person_add.html'
    form_class = PersonModelForm

    def get_success_url(self):
        return reverse_lazy('contact:list')


class UpdatePersonView(UpdateView):
    template_name = 'contact/person_update.html'
    form_class = PersonModelForm
    queryset = Person.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Person, id=id_)

    def get_success_url(self):
        return reverse_lazy('contact:list')


class PersonDeleteView(DeleteView):
    template_name = 'contact/person_delete.html'
    fail_url = 'contact/person_delete_fail.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Person, id=id_)

    def get_success_url(self):
        return reverse_lazy('contact:list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        fail_url = self.fail_url
        if Phone.objects.filter(person=self.object) or Email.objects.filter(person=self.object):
            return render(request, fail_url)
        else:
            self.object.delete()
            return redirect(success_url)


class PhoneAddView(CreateView):
    template_name = 'contact/phone_add.html'
    form_class = PhoneModelForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.person = Person.objects.get(id=self.kwargs.get("id"))
        self.object = obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('contact:list')


class PhoneDeleteView(DeleteView):
    template_name = 'contact/phone_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Phone, id=id_)

    def get_success_url(self):
        return reverse_lazy('contact:list')


class EmailAddView(CreateView):
    template_name = 'contact/email_add.html'
    form_class = EmailModelForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.person = Person.objects.get(id=self.kwargs.get("id"))
        self.object = obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('contact:list')


class EmailDeleteView(DeleteView):
    template_name = 'contact/email_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Email, id=id_)

    def get_success_url(self):
        return reverse_lazy('contact:list')

contacts/pages/views.py
from django.shortcuts import render


def home_view(request, *args, **kwargs):
    return render(request, 'home.html', {})

contacts/contact/templates/contact/email_add.html
{% extends 'base.html' %}

{% block content %}
<h1>Add email:</h1>
<form method='POST'> 
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
</form>
{% endblock %}

contacts/contact/templates/contact/email_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Do you want to delete {{ object.email }} from contact {{ object.person.name }} {{ object.person.surname }}:</h1>
<form method='POST'> 
    {% csrf_token %}
    <input type='submit' value='Yes' /> <a href="{% url 'contact:list' %}"><input type='button' value='Cancel' /></a> 
</form>
{% endblock %}

contacts/contact/templates/contact/person_add.html
{% extends 'base.html' %}

{% block content %}
<h1>New Contact:</h1>
<form method='POST'> 
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
</form>
{% endblock %}

contacts/contact/templates/contact/person_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Do you want to delete contact: "{{ object.name }} {{ object.surname }}"</h1>
<form method='POST'> 
    {% csrf_token %}
    <input type='submit' value='Yes' /> <a href="{% url 'contact:list' %}"><input type='button' value='Cancel' /></a> 
</form>
{% endblock %}

contacts/contact/templates/contact/person_delete_fail.html
{% extends 'base.html' %}

{% block content %}
<h1>Cannot remove contact with email/phone assigned</h1>
<a href="{% url 'contact:list' %}"><input type='button' value='Ok' /></a> 
{% endblock %}

contacts/contact/templates/contact/person_update.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit contact:</h1>
<form method='POST'> 
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
</form>
{% endblock %}

contacts/contact/templates/contact/phone_add.html
{% extends 'base.html' %}

{% block content %}
<h1>Add Phone no.:</h1>
<form method='POST'> 
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
</form>
{% endblock %}

contacts/contact/templates/contact/phone_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Do you want to delete {{ object.phone }} from contact {{ object.person.name }} {{ object.person.surname }}:</h1>
<form method='POST'> 
    {% csrf_token %}
    <input type='submit' value='Yes' /> <a href="{% url 'contact:list' %}"><input type='button' value='Cancel' /></a> 
</form>
{% endblock %}

contacts/contact/templates/list.html
{% extends 'base.html' %}

{% block content %}
<hx>Contacts:</hx>
<form method="GET" action="">
    <input type="text" name="q" placeholder="Search contacts" 
            value="{{ request.GET.q }}" incremental="incremental" />
    <input type="submit" value="Search" />
</form>
<ul>
    {% for obj in object_list %}
        <li>
            {{ obj.name }} {{ obj.surname }}
            <a href="{{ obj.update_url }}"><input type="button" value="Edit"></a>
            <a href="{{ obj.phone_add_url }}"><input type="button" value="+ Phone"></a>
            <a href="{{ obj.email_add_url }}"><input type="button" value="+ Email"></a>
            <a href="{{ obj.delete_url }}"><input type="button" value="Delete"></a>
            {% for p in obj.phone %}
            <ul>
                <li>
                    {{ p.phone }}
                    <a href="{{ p.delete_url }}"><input type="button" value="Delete"></a>
                </li>
            </ul>
            {% endfor %}
            {% for e in obj.email %}
            <ul>
                <li>
                    {{ e.email }}
                    <a href="{{ e.delete_url }}"><input type="button" value="Delete"></a>
                </li>
            </ul>
            {% endfor %}
        </li>
    {% endfor %}
    <a href="{% url 'contact:person-add' %}"><input type="button" value="Add contact"></a>
</ul>
{% endblock %}

contacts/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Ansta - contacts</title>
    </head>
    <body>
        {% include 'navigation.html' %}
        {% block content %}
        {% endblock %}
    </body>
</html>

contacts/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome</h1>
{% endblock %}

contacts/templates/navigation.html
<nav>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'contact:list' %}">Contacts</a></li>
    </ul>
</nav>